### ISSUE TITLE
How is the private key derived from the app icon

### ISSUE THREAD

**Issue by magnusart** [falk/danskebank-api#1]
Hi

I'm currently reverse engineering the DDB mobile API myself and saw this in your code: 
https://github.com/falk/danskebank-api/blob/88a5b8b231d8e2184ac2c62bcb2fe38bf400792f/dkbank.py#L17

Could you expand on the algorithm that expands the private key from the app icon?

**Comment by liato** [comment]
@magnusart There are two constant values defined in the app that are used for the public keys. One that produces the public key for messages sent during BankID auth and one for the public key that is used to encrypt the `Token`.

To generate the public keys an icon is read from assets (`assets/icon.png`), the bytes read from the icon are trimmed to the same length as the constant values and modified a bit and as a last step the byte arrays from the constant value and the app icon are XORed to produce the final public key.

Instead of doing all of this it's much easier to just log the public key when it's being used.

Let me know if you need any help!

**Comment by magnusart** [comment]
Hi @liato 

Thanks, could you please describe how did you go about to log the key? 

**What I have done so far:**
I have disassembled the app so I can do static analysis. I have disassembled both to Java and Smali but I didn't have any success in reassembling the Smali code in order to debug. It complains that some source is missing (don't remember in detail).

What I did do was to set up a SSL man in the middle proxy (Charles). This works well, since the app sends statistics when I navigate it enabled me to decipher which APIs in the application was being used via manual analysis of the Java Source code. 

I can see the encrypted response (?) to the magic key but the public key is hidden from me. My next step would been to have reimplement the logic from the app from the disassembled Java code, which is a pain but doable.

**Edit:** Googled a bit, are you using Xposed Bridge, if so could you please give a quick overview on what steps you took (specific class/method etc)? https://github.com/rovo89/XposedBridge/wiki/Development-tutorial

**Comment by falk** [comment]
Sorry for the late reply.
I actually can not remember how I extracted the key. It was either by static analysis or by patching the smali to log the key as liato mentions.

**Comment by magnusart** [comment]
OK. I've looked at the new app in the mean time. They use React Native now. The new security model is to eval a piece javascript code sent from their servers in order to produce a key and initiate a session. Unorthodox but effective. If you mimic it you've potentially allowed a backdoor into your code.
